fix(v8): fix spawning of subprocesses
nodejs/node-core-utils pull request #726
Opened 2023-09-11 10:47 UTC by aduh95

Refs: https://github.com/nodejs/node-core-utils/pull/722#issuecomment-1706027683

2023-09-11 11:31 UTC, MoLow approved these changes
LGTM, maybe we should add tests for these flows

2023-09-11 11:56 UTC, targos requested changes
Still not quite right:

- Output from git command appears in the terminal
- Error is still here

```
$ node /Users/mzasso/git/nodejs/node-core-utils/bin/git-node.js v8 --v8-dir ~/git/chromium/v8/v8 major
❯ Update local V8 clone
  ⠸ Fetch V8
❯ Update local V8 clone
❯ Update local V8 clone
  ⠴ Fetch V8
◼ Major V8 update
◼ Update V8 version in maintaining-dependencies.md
◼ Commit V8 update
◼ Update version numbers
From https://chromium.googlesource.com/v8/v8
 * [new branch]              11.9.50                -> origin/11.9.50
 * [new branch]              11.9.51                -> origin/11.9.51
 + bd2ab654247...eb941aa621b canary                 -> origin/canary  (forced update)
   4f2f8661fa4..5513eb17d41  lkgr                   -> origin/lkgr
   85d36de7fb4..36d5e54d760  main                   -> origin/main
 + bd2ab654247...eb941aa621b roll                   -> origin/roll  (forced update)
✔ Update local V8 clone
❯ Major V8 update
✔ Update local V8 clone
❯ Major V8 update
  ✔ Get current V8 version
  ⠙ Checkout V8 branch
  ◼ Remove deps/v8
  ◼ Clone branch to deps/v8
  ◼ Remove deps/v8/.git
  ◼ Track all files in deps/v8
  ◼ Update V8 DEPS
  ◼ Apply Node-specific changes
◼ Update V8 version in maintaining-dependencies.md
◼ Commit V8 update
◼ Update version numbers
error: branch '11.9.51' not found
```

2023-09-11 11:57 UTC, targos commented
> maybe we should add tests for these flows

Certainly, but that's not easy to do (and V8 repo takes a very long time to clone).

2023-09-12 12:23 UTC, targos commented
It's better (doesn't fail anymore), but the `git` output is still piped to stdout:

<details>

```
$ node /Users/mzasso/git/nodejs/node-core-utils/bin/git-node.js v8 --v8-dir ~/git/chromium/v8/v8 major
❯ Update local V8 clone
  ⠏ Fetch V8
◼ Major V8 update
❯ Update local V8 clone
❯ Update local V8 clone
  ⠹ Fetch V8
◼ Major V8 update
◼ Update V8 version in maintaining-dependencies.md
◼ Commit V8 update
◼ Update version numbers
From https://chromium.googlesource.com/v8/v8
   466870172c6..641c7c3a2b4  11.8-lkgr              -> origin/11.8-lkgr
 * [new branch]              11.9.52                -> origin/11.9.52
 * [new branch]              11.9.53                -> origin/11.9.53
 * [new branch]              11.9.54                -> origin/11.9.54
 * [new branch]              11.9.55                -> origin/11.9.55
 * [new branch]              11.9.56                -> origin/11.9.56
 * [new branch]              11.9.57                -> origin/11.9.57
 * [new branch]              11.9.58                -> origin/11.9.58
 * [new branch]              11.9.59                -> origin/11.9.59
 * [new branch]              11.9.60                -> origin/11.9.60
 * [new branch]              11.9.61                -> origin/11.9.61
 * [new branch]              11.9.62                -> origin/11.9.62
 * [new branch]              11.9.63                -> origin/11.9.63
 * [new branch]              11.9.64                -> origin/11.9.64
 * [new branch]              11.9.65                -> origin/11.9.65
❯ Update local V8 clone
  ⠸ Fetch V8
◼ Major V8 update
◼ Update V8 version in maintaining-dependencies.md
◼ Commit V8 update
◼ Update version numbers
 * [new branch]              chromium/6003          -> origin/chromium/6003
 * [new branch]              chromium/6004          -> origin/chromium/6004
   5513eb17d41..2b291d26667  lkgr                   -> origin/lkgr
   36d5e54d760..6b0da734ac6  main                   -> origin/main
 + eb941aa621b...62f3bcceef9 roll                   -> origin/roll  (forced update)
   c3f31220d0e..641c7c3a2b4  refs/branch-heads/11.8 -> branch-heads/11.8
 * [new tag]                 11.8.172.2-pgo         -> 11.8.172.2-pgo
 * [new tag]                 11.8.172.3             -> 11.8.172.3
 * [new tag]                 11.8.172.3-pgo         -> 11.8.172.3-pgo
 * [new tag]                 11.9.51-pgo            -> 11.9.51-pgo
 * [new tag]                 11.9.52                -> 11.9.52
 * [new tag]                 11.9.52-pgo            -> 11.9.52-pgo
 * [new tag]                 11.9.53                -> 11.9.53
 * [new tag]                 11.9.53-pgo            -> 11.9.53-pgo
 * [new tag]                 11.9.54                -> 11.9.54
 * [new tag]                 11.9.54-pgo            -> 11.9.54-pgo
 * [new tag]                 11.9.55                -> 11.9.55
 * [new tag]                 11.9.55-pgo            -> 11.9.55-pgo
 * [new tag]                 11.9.56                -> 11.9.56
 * [new tag]                 11.9.56-pgo            -> 11.9.56-pgo
 * [new tag]                 11.9.57                -> 11.9.57
 * [new tag]                 11.9.57-pgo            -> 11.9.57-pgo
 * [new tag]                 11.9.58                -> 11.9.58
 * [new tag]                 11.9.58-pgo            -> 11.9.58-pgo
 * [new tag]                 11.9.59                -> 11.9.59
 * [new tag]                 11.9.59-pgo            -> 11.9.59-pgo
 * [new tag]                 11.9.60                -> 11.9.60
 * [new tag]                 11.9.60-pgo            -> 11.9.60-pgo
 * [new tag]                 11.9.61                -> 11.9.61
 * [new tag]                 11.9.61-pgo            -> 11.9.61-pgo
 * [new tag]                 11.9.62                -> 11.9.62
 * [new tag]                 11.9.62-pgo            -> 11.9.62-pgo
 * [new tag]                 11.9.63                -> 11.9.63
 * [new tag]                 11.9.63-pgo            -> 11.9.63-pgo
 * [new tag]                 11.9.64                -> 11.9.64
✔ Update local V8 clone
❯ Major V8 update
✔ Update local V8 clone
✔ Update local V8 clone
✔ Update local V8 clone
✔ Update local V8 clone
✔ Update local V8 clone
✔ Update local V8 clone
❯ Major V8 update
  ✔ Get current V8 version
  ✔ Checkout V8 branch
  ✔ Remove deps/v8
  ✔ Clone branch to deps/v8
✔ Update local V8 clone
✔ Update local V8 clone
❯ Major V8 update
  ✔ Get current V8 version
  ✔ Checkout V8 branch
  ✔ Remove deps/v8
✔ Update local V8 clone
❯ Major V8 update
✔ Update local V8 clone
❯ Major V8 update
  ✔ Get current V8 version
  ✔ Checkout V8 branch
  ✔ Remove deps/v8
  ✔ Clone branch to deps/v8
✔ Update local V8 clone
✔ Update local V8 clone
❯ Major V8 update
✔ Update local V8 clone
✔ Update local V8 clone
❯ Major V8 update
  ✔ Get current V8 version
  ✔ Checkout V8 branch
✔ Update local V8 clone
❯ Major V8 update
✔ Update local V8 clone
❯ Major V8 update
  ✔ Get current V8 version
  ✔ Checkout V8 branch
  ✔ Remove deps/v8
✔ Update local V8 clone
❯ Major V8 update
  ✔ Get current V8 version
  ✔ Checkout V8 branch
✔ Update local V8 clone
❯ Major V8 update
  ✔ Get current V8 version
✔ Update local V8 clone
✔ Major V8 update
✔ Update V8 version in maintaining-dependencies.md
⠸ Commit V8 update
◼ Update version numbers
warning: in the working copy of 'deps/v8/third_party/ittapi/include/fortran/win32/ittnotify.f90', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'deps/v8/third_party/ittapi/src/ittnotify/ittptmark32.S', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'deps/v8/third_party/ittapi/src/ittnotify/ittptmark32.asm', CRLF will be replaced by LF the next time Git touches it
warning: in the working copy of 'deps/v8/third_party/ittapi/src/ittnotify/ittptmark64.S', CRLF will be replaced by LF the n
✔ Update local V8 clone
✔ Update local V8 clone
✔ Major V8 update
✔ Update V8 version in maintaining-dependencies.md
⠙ Commit V8 update
◼ Update version numbers
 3408 files changed, 252666 insertions(+), 141149 deletions(-)
 create mode 100644 deps/v8/bazel/BUILD.ittapi
 create mode 100644 deps/v8/gni/Info.plist
 create mode 100644 deps/v8/include/v8-handle-base.h
 create mode 100644 deps/v8/include/v8-source-location.h
 create mode 100644 deps/v8/src/base/discriminated-union.h
 create mode 100644 deps/v8/src/base/intrusive-set.h
 create mode 100644 deps/v8/src/base/platform/platform-win32.h
 create mode 100644 deps/v8/src/base/small-map.h
 create mode 100644 deps/v8/src/builtins/js-to-wasm.tq
 create mode 100644 deps/v8/src/builtins/map-groupby.tq
 create mode 100644 deps/v8/src/builtins/object-groupby.tq
 create mode 100644 deps/v8/src/builtins/promise-withresolvers.tq
 create mode 100644 deps/v8/src/builtins/set-difference.tq
 create mode 100644 deps/v8/src/builtins/set-intersection.tq
 create mode 100644 deps/v8/src/builtins/set-is-disjoint-from.tq
 create mode 100644 deps/v8/src/builtins/set-is-subset-of.tq
 create mode 100644 deps/v8/src/builtins/set-is-superset-of.tq
 create mode 100644 deps/v8/src/builtins/set-symmetric-difference.tq
 create mode 100644 deps/v8/src/builtins/set-union.tq
 create mode 100644 deps/v8/src/builtins/wasm-strings.tq
 create mode 100644 deps/v8/src/builtins/wasm-to-js.tq
 create mode 100644 deps/v8/src/codegen/linkage-location.h
 create mode 100644 deps/v8/src/codegen/reloc-info-inl.h
 delete mode 100644 deps/v8/src/codegen/string-constants.cc
 delete mode 100644 deps/v8/src/codegen/string-constants.h
 create mode 100644 deps/v8/src/compiler/backend/instruction-selector-adapter.h
 create mode 100644 deps/v8/src/compiler/js-heap-broker-inl.h
 create mode 100644 deps/v8/src/compiler/pair-load-store-reducer.cc
 create mode 100644 deps/v8/src/compiler/pair-load-store-reducer.h
 create mode 100644 deps/v8/src/compiler/turboshaft/debug-feature-lowering-phase.cc
 rename deps/v8/src/compiler/turboshaft/{tag-untag-lowering-phase.h => debug-feature-lowering-phase.h} (50%)
 create mode 100644 deps/ [...]

2023-09-12 13:43 UTC, targos approved these changes
LGTM with my last commit. Git output is no longer intertwined with Listr

2023-09-12 20:31 UTC, merged